# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb1b177d46427dade4ac7bb9fa2ff13422edd3064f95882a7d5bd501fabdba212cace495e63144c6e078f2338ac274e43a5e9691a0fec60701f726178b8710c

test:
  secret_key_base: 7fe7eb9a36bccc7cf1bc34e5f2d8ab12ec937de4069db175a1ce89bea6d2f5d1f5cb33648f1ccf0ddff8475fb105c60a4e12b79c4445633b87ed5ad96cbb90bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
